# Generated by Django 4.2.11 on 2024-03-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن')),
                ('picture', models.FileField(blank=True, upload_to='Personality_Information_picture/', verbose_name='تصویر کاربری')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرد ')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات کاربران',
                'db_table': 'Personality_Information',
            },
        ),
    ]
