# Generated by Django 4.2.11 on 2024-03-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(max_length=100, verbose_name='معرفی نامه')),
                ('my_team_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.personality_information')),
            ],
            options={
                'verbose_name_plural': 'اعضای تیم ',
                'db_table': 'My_Team',
            },
        ),
    ]
