# Generated by Django 4.2.11 on 2024-03-20 12:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='project_picture/', verbose_name='تصویر ')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن ۱ ')),
                ('texhnology', models.CharField(help_text='لطفا با ویرگول از هم جدا کنید ', max_length=100, verbose_name='فناوری ها ')),
                ('time', models.IntegerField(verbose_name='زمان ')),
                ('team_support', models.CharField(max_length=100, verbose_name='عنوان تیم کمک کننده')),
            ],
            options={
                'verbose_name_plural': 'پروژه های تیم مکا',
                'db_table': 'Project_information',
            },
        ),
    ]
