# Generated by Django 4.2.11 on 2024-03-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_information',
            name='time',
            field=models.CharField(verbose_name='زمان '),
        ),
    ]
