# Generated by Django 4.2.11 on 2024-03-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل عضویت در خبرنامه')),
            ],
            options={
                'verbose_name_plural': 'اعضای خبرنامه ',
                'db_table': 'News_Letter',
            },
        ),
    ]
