# Generated by Django 4.2.11 on 2024-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_letter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل عضویت در خبرنامه'),
        ),
    ]
