# Generated by Django 4.2.11 on 2024-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام حقوقی شرکت')),
                ('picture', models.FileField(upload_to='Company_Customers_picture', verbose_name='لوگوی شرکت')),
            ],
            options={
                'verbose_name_plural': 'مشتریان سازمانی مکا',
                'db_table': 'Companies',
            },
        ),
    ]
