# Generated by Django 4.2.11 on 2024-03-15 11:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_my_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(help_text='این فیلد به طور خودکار مقدار دهی میشود', unique=True, verbose_name='ادرس اینترنتی دسته بندی')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی های مقالات',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تگ های مقالات')),
                ('slug', models.SlugField(help_text='به طور خودکار مقدار دهی میشود', unique=True, verbose_name='آدرس اینترنتی تگ های مقالات')),
            ],
            options={
                'verbose_name_plural': 'تگ های مقالات',
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='Post_Pictures/', verbose_name='تصویر مقاله')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.my_team', verbose_name='عضو تیم ')),
                ('category_this_post', models.ForeignKey(help_text='این فیلد از قسمت دسته بندی ها انتخاب میشود', on_delete=django.db.models.deletion.CASCADE, to='Blog.category', verbose_name='دسته بندی موضوع')),
                ('tags', models.ManyToManyField(to='Blog.tags', verbose_name='تگ های مقالات')),
            ],
            options={
                'verbose_name_plural': 'مقالات وبسایت',
                'db_table': 'Post',
            },
        ),
    ]
