# Generated by Django 4.2.11 on 2024-03-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_edited_alter_post_tags_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_read_duration',
            field=models.IntegerField(null=True, verbose_name='مدت زمان تخمینی مطالعه مقاله'),
        ),
    ]
