# Generated by Django 4.2.11 on 2024-03-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_my_team_idea_about_website'),
        ('Blog', '0004_post_time_read_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نظر دهنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل نظر دهنده')),
                ('text', models.TextField(verbose_name='متن نظر مخاطب')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال نظر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.post', verbose_name='انتخاب مقاله مورد نظر')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.personality_information', verbose_name='فرد نظر دهنده')),
            ],
            options={
                'verbose_name_plural': 'کامنت های مخاطبین',
                'db_table': 'Comments_Post',
            },
        ),
    ]
