# Generated by Django 4.2.11 on 2024-03-18 14:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن ۲ در صورت وجود داشتن لازم '),
        ),
    ]
