# Generated by Django 4.2.11 on 2024-03-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_post_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_post',
            name='writer',
        ),
    ]
