# Generated by Django 4.2.11 on 2024-03-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_remove_comments_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=50, null=True, verbose_name='خلاصه متن مروری در 30 کلمه'),
        ),
    ]
