# Generated by Django 4.2.11 on 2024-03-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس ما')),
                ('email1', models.EmailField(max_length=254, verbose_name='ایمیل اول ما')),
                ('email2', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل دوم ما')),
                ('tel1', models.CharField(max_length=11, verbose_name='تلفن ۱ ما')),
                ('tel2', models.CharField(max_length=11, verbose_name='تلفن ۲ ما')),
                ('address_map', models.CharField(help_text='با استفاده از نقشه گوگل مشخصات باید وارد بشود . ', max_length=1000, verbose_name='آدرس ما از روی نقشه ')),
                ('instagram', models.CharField(max_length=200, verbose_name='آدرس ما در اینستاگرام')),
                ('gmail', models.CharField(max_length=200, verbose_name='آدرس ایمیل ما')),
                ('telegram', models.CharField(blank=True, max_length=200, verbose_name='آدرس ما در تلگرام')),
                ('face_book', models.CharField(blank=True, max_length=200, verbose_name='آدرس ما در فیسبوک')),
                ('linkedin', models.CharField(max_length=200, verbose_name='آدرس ما در لینکدین')),
            ],
            options={
                'verbose_name_plural': 'مشخصات و اطلاعات ما',
                'db_table': 'Company_Information',
            },
        ),
    ]
