# Generated by Django 4.2.11 on 2024-03-18 19:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم خدمت')),
                ('picture', models.FileField(upload_to='service_picture/', verbose_name='تصویر خدمت')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن توضیحات')),
            ],
            options={
                'verbose_name_plural': 'خدمات شرکت مکا ',
                'db_table': 'Service_Information',
            },
        ),
    ]
