# Generated by Django 4.2.11 on 2024-03-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_information',
            name='introduce',
            field=models.CharField(max_length=100, null=True, verbose_name='معرفی نامه خدمت'),
        ),
        migrations.AddField(
            model_name='service_information',
            name='picture2',
            field=models.FileField(null=True, upload_to='service_picture/', verbose_name='تصویر خدمت ۲'),
        ),
    ]
