# Generated by Django 4.2.11 on 2024-03-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم تصویر')),
                ('picture', models.FileField(upload_to='slider_picture', verbose_name='تصویر مورد نظر ')),
            ],
            options={
                'verbose_name_plural': 'تصاویر اسلایدر صفحه اول سایت',
                'db_table': 'Picture_Slider',
            },
        ),
    ]
