# Generated by Django 4.2.11 on 2024-03-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_slider',
            name='text',
            field=models.CharField(max_length=50, null=True, verbose_name='متن اسلایدر'),
        ),
        migrations.CreateModel(
            name='SELECT_PICTURE_SLIDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(help_text='یک اسلایدر برای نمایش در صفحه اول مشخص کنید', on_delete=django.db.models.deletion.CASCADE, to='home.picture_slider', verbose_name='انتخاب اسلایدر برای نمایش ')),
            ],
            options={
                'verbose_name_plural': 'انتخاب اسلایدر برای نمایش درصفحه اول',
                'db_table': 'SELECT_PICTURE_SLIDER',
            },
        ),
    ]
